keur diajar github
nandirchrd/CSS-Grid pull request #1
Opened 2023-05-13 18:16 UTC by RamaNuril

acc bro

2023-05-14 17:26 UTC, nandirchrd requested changes
Cek 123

2023-05-14 17:30 UTC, nandirchrd commented on index.html
> +<body>
Tambah Nasi Padang

2023-05-14 17:30 UTC, nandirchrd requested changes
Kurang nasi padang

2023-05-14 18:30 UTC, RamaNuril commented on index.html
> +<body>
oke mantap nambah padang siap

2023-05-14 18:37 UTC, RamaNuril commented on index.html
> +    <h1>Nasi Padang</h1>
oke udh bro

2023-05-15 03:03 UTC, nandirchrd commented on index.html
> +    <h1>Nasi Padang</h1>
Ok 👌

2023-05-15 03:08 UTC, nandirchrd approved these changes
![images (14)](https://github.com/nandirchrd/css-grid/assets/94351277/6debb284-6c0e-4149-b56d-e78eca393c02)

2023-05-15 03:10 UTC, merged